<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAsArray($colonne, $order, $search=null){
        $qb = $this->createQueryBuilder('p');
        if(!empty($search)) {
            $qb->where('p.title LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        $query = $qb
            ->orderBy("p.".$colonne, $order)
                // ->andWhere('p.price >50')
            ->getQuery();

        return $query->getArrayResult();

    }
}
